'use client';

import { Work, Author } from '@/lib/types';
import { motion } from 'framer-motion';
import { useEffect, useRef } from 'react';

interface TimelineViewProps {
    works: (Work & { author?: Author })[];
}

export default function TimelineView({ works }: TimelineViewProps) {
    const sortedWorks = [...works].sort((a, b) => a.year - b.year);
    const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add('animate-slide-up');
                    }
                });
            },
            { threshold: 0.1 }
        );

        const items = containerRef.current?.querySelectorAll('.timeline-item');
        items?.forEach((item) => observer.observe(item));

        return () => observer.disconnect();
    }, []);

    return (
        <div ref={containerRef} className="relative max-w-4xl mx-auto px-4">
            {/* Vertical line */}
            <div className="absolute left-8 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary via-secondary to-accent opacity-30 hidden md:block" />

            <div className="space-y-8">
                {sortedWorks.map((work, index) => (
                    <motion.div
                        key={work.id}
                        initial={{ opacity: 0, x: index % 2 === 0 ? -50 : 50 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.1 }}
                        className="timeline-item relative"
                    >
                        {/* Timeline dot */}
                        <div className="absolute left-8 w-4 h-4 rounded-full bg-primary shadow-lg shadow-primary/50 border-4 border-background hidden md:block -ml-2 mt-6" />

                        <div className="md:ml-20 glass rounded-xl p-6 glass-hover group">
                            <div className="flex flex-col sm:flex-row gap-4">
                                {/* Preview image placeholder - will be generated by AI */}
                                <div className="w-full sm:w-32 h-32 rounded-lg bg-gradient-to-br from-primary/20 to-secondary/20 flex-shrink-0 flex items-center justify-center overflow-hidden group-hover:scale-105 transition-transform">
                                    <div className="text-4xl">📚</div>
                                </div>

                                <div className="flex-1 space-y-2">
                                    <div className="flex items-start justify-between gap-4 flex-wrap">
                                        <h3 className="text-xl font-serif font-bold text-foreground group-hover:text-gradient transition-all">
                                            {work.title}
                                        </h3>
                                        <span className="px-3 py-1 rounded-full bg-primary/20 text-primary text-sm font-medium flex-shrink-0">
                                            {work.year}
                                        </span>
                                    </div>

                                    <p className="text-muted-foreground">
                                        by <span className="text-foreground font-medium">{work.author?.name || 'Unknown'}</span>
                                    </p>

                                    <p className="text-sm text-muted-foreground">
                                        Published: {work.publicationDate}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                ))}
            </div>

            {sortedWorks.length === 0 && (
                <div className="text-center py-12 text-muted-foreground">
                    No works found in this timeline
                </div>
            )}
        </div>
    );
}
